name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore user-service/UserService.API/UserService.API.sln
    - name: Build
      run: dotnet build user-service/UserService.API/UserService.API.sln --no-restore
    - name: Test
      run: dotnet test user-service/UserService.API/UserService.API.sln --no-build --verbosity normal
